class SuraDetails {
  final int suraNumber;
  final String tamilName;
  final String? tamilMeaning;
  final String arabicName;
  final int verseCount;

  SuraDetails({
    required this.suraNumber,
    required this.tamilName,
    this.tamilMeaning,
    required this.arabicName,
    required this.verseCount,
  });

  static List<SuraDetails> suraList = [
    SuraDetails(
        suraNumber: 1,
        tamilName: 'අල්-ෆාතිහා',
        tamilMeaning: 'ආරම්භය',
        arabicName: 'الفاتحة',
        verseCount: 7),
    SuraDetails(
        suraNumber: 2,
        tamilName: 'අල්-බකරා',
        tamilMeaning: 'එළදෙන',
        arabicName: 'البقرة',
        verseCount: 286),
    SuraDetails(
        suraNumber: 3,
        tamilName: 'ආල ඉම්රාන්',
        arabicName: 'آل عمران',
        verseCount: 200),
    SuraDetails(
        suraNumber: 4,
        tamilName: 'අන්නිසා',
        tamilMeaning: 'කාන්තාවන්',
        arabicName: 'النساء',
        verseCount: 176),
    SuraDetails(
        suraNumber: 5,
        tamilName: 'අල්-මායිදා',
        tamilMeaning: 'ආහාර බන්දේසිය',
        arabicName: 'المائدة',
        verseCount: 120),
    SuraDetails(
        suraNumber: 6,
        tamilName: 'අල්-අන්ආම්',
        tamilMeaning: 'එළු, ගව, ඔටුවන් වැනි සතුන්',
        arabicName: 'الأنعام',
        verseCount: 165),
    SuraDetails(
        suraNumber: 7,
        tamilName: 'අල්-අඅරාෆ්',
        tamilMeaning: 'සිකරය',
        arabicName: 'الأعراف',
        verseCount: 206),
    SuraDetails(
        suraNumber: 8,
        tamilName: 'අල්-අන්ෆාල්',
        tamilMeaning: 'යුද්ධාජිද වස්තූන්',
        arabicName: 'الأنفال',
        verseCount: 75),
    SuraDetails(
        suraNumber: 9,
        tamilName: 'අත්තව්බා',
        tamilMeaning: 'පසුතැවිල්ල',
        arabicName: 'التوبة',
        verseCount: 129),
    SuraDetails(
        suraNumber: 10,
        tamilName: 'යූනුස්',
        arabicName: 'يونس',
        verseCount: 109),
    SuraDetails(
        suraNumber: 11,
        tamilName: 'හූද්',
        arabicName: 'هود',
        verseCount: 123),
    SuraDetails(
        suraNumber: 12,
        tamilName: 'යූසුෆ්',
        arabicName: 'يوسف',
        verseCount: 111),
    SuraDetails(
        suraNumber: 13,
        tamilName: 'අර්රඅද්',
        tamilMeaning: 'හෙණ හඬ',
        arabicName: 'الرعد',
        verseCount: 43),
    SuraDetails(
        suraNumber: 14,
        tamilName: 'ඉබ්රාහීම්',
        arabicName: 'ابراهيم',
        verseCount: 52),
    SuraDetails(
        suraNumber: 15,
        tamilName: 'අල්-හිජ්ර්',
        tamilMeaning: 'ගල් තලාව',
        arabicName: 'الحجر',
        verseCount: 99),
    SuraDetails(
        suraNumber: 16,
        tamilName: 'අන්නහ්ල්',
        tamilMeaning: 'මී මැස්සා',
        arabicName: 'النحل',
        verseCount: 128),
    SuraDetails(
        suraNumber: 17,
        tamilName: 'බනී ඉස්රායීල්',
        tamilMeaning: 'ඉස්රායීල පරම්පරාවේ දරුවන්',
        arabicName: 'الإسراء',
        verseCount: 111),
    SuraDetails(
        suraNumber: 18,
        tamilName: 'අල්-කහ්ෆ්',
        tamilMeaning: 'ගුහාව',
        arabicName: 'الكهف',
        verseCount: 110),
    SuraDetails(
        suraNumber: 19,
        tamilName: 'මර්යම්',
        arabicName: 'مريم',
        verseCount: 98),
    SuraDetails(
        suraNumber: 20,
        tamilName: 'තා හා',
        arabicName: 'طه',
        verseCount: 135),
    SuraDetails(
        suraNumber: 21,
        tamilName: 'අල් අන්බියා',
        tamilMeaning: 'නබිවරුන්',
        arabicName: 'الأنبياء',
        verseCount: 112),
    SuraDetails(
        suraNumber: 22,
        tamilName: 'අල් හජ්',
        tamilMeaning: 'වන්ඳනාව',
        arabicName: 'الحج',
        verseCount: 78),
    SuraDetails(
        suraNumber: 23,
        tamilName: 'අල් මුඋමිනූන්',
        tamilMeaning: 'විශ්වාසවන්තයින්',
        arabicName: 'المؤمنون',
        verseCount: 118),
    SuraDetails(
        suraNumber: 24,
        tamilName: 'අල් නූර්',
        tamilMeaning: 'ආලෝකය',
        arabicName: 'النور',
        verseCount: 64),
    SuraDetails(
        suraNumber: 25,
        tamilName: 'අල් ෆුර්කාන්',
        tamilMeaning: '(පින් පව්) වෙන්කර දැනුම් දෙන (අල්-කුර්ආනය)',
        arabicName: 'الفرقان',
        verseCount: 77),
    SuraDetails(
        suraNumber: 26,
        tamilName: 'අල් ෂුඅරාඋ',
        tamilMeaning: 'කිවිඳියන්',
        arabicName: 'الشعراء',
        verseCount: 227),
    SuraDetails(
        suraNumber: 27,
        tamilName: 'අල් නම්ල්',
        tamilMeaning: 'කුහුඹුවා',
        arabicName: 'النمل',
        verseCount: 93),
    SuraDetails(
        suraNumber: 28,
        tamilName: 'අල් කසස්',
        tamilMeaning: 'ඉතිහාසයන්',
        arabicName: 'القصص',
        verseCount: 88),
    SuraDetails(
        suraNumber: 29,
        tamilName: 'අල් අන්කබූත්',
        tamilMeaning: 'මකුළුවා',
        arabicName: 'العنكبوت',
        verseCount: 69),
    SuraDetails(
        suraNumber: 30,
        tamilName: 'අර්-රූම්',
        tamilMeaning: 'රෝමවරුන්',
        arabicName: 'الروم',
        verseCount: 60),
    SuraDetails(
        suraNumber: 31,
        tamilName: 'ලුක්මාන්',
        arabicName: 'لقمان',
        verseCount: 34),
    SuraDetails(
        suraNumber: 32,
        tamilName: 'අල් සජදා',
        tamilMeaning: 'නළල බිම තබා නැමදීම',
        arabicName: 'السجدة',
        verseCount: 30),
    SuraDetails(
        suraNumber: 33,
        tamilName: 'අල් අහ්සාබ්',
        tamilMeaning: 'සහායයන්',
        arabicName: 'الأحزاب',
        verseCount: 73),
    SuraDetails(
        suraNumber: 34, tamilName: 'සබා',
        arabicName: 'سبإ',
        verseCount: 54),
    SuraDetails(
        suraNumber: 35,
        tamilName: 'ෆාතිර්',
        tamilMeaning: 'උත්පාදකයා',
        arabicName: 'فاطر',
        verseCount: 45),
    SuraDetails(
        suraNumber: 36, tamilName: 'යාසීන්',
        arabicName: 'يس',
        verseCount: 83),
    SuraDetails(
        suraNumber: 37,
        tamilName: 'අස්සාෆ්ෆාත්',
        tamilMeaning: 'පෙළ ගැසී ඇති කණ්ඩායම්',
        arabicName: 'الصافات',
        verseCount: 182),
    SuraDetails(
        suraNumber: 38,
        tamilName: 'සාද්',
        arabicName: 'ص',
        verseCount: 88),
    SuraDetails(
        suraNumber: 39,
        tamilName: 'අල් සුමර්',
        tamilMeaning: 'සමූහයන්',
        arabicName: 'الزمر',
        verseCount: 75),
    SuraDetails(
        suraNumber: 40,
        tamilName: 'අල් මුඋමින්',
        tamilMeaning: 'විශ්වාස කරන්නා',
        arabicName: 'غافر',
        verseCount: 85),
    SuraDetails(
        suraNumber: 41,
        tamilName: 'හා. මීම්. අල් සජ්දා',
        arabicName: 'فصلت',
        verseCount: 54),
    SuraDetails(
        suraNumber: 42,
        tamilName: 'අෂ්ෂූරා',
        tamilMeaning: 'සාකච්චාව',
        arabicName: 'الشورى',
        verseCount: 53),
    SuraDetails(
        suraNumber: 43,
        tamilName: 'අස්සුක්රුෆ්',
        tamilMeaning: 'රණ් ආභරණ',
        arabicName: 'الزخرف',
        verseCount: 89),
    SuraDetails(
        suraNumber: 44,
        tamilName: 'අද්දුකාන්',
        tamilMeaning: 'දුමාරය',
        arabicName: 'الدخان',
        verseCount: 59),
    SuraDetails(
        suraNumber: 45,
        tamilName: 'අල් ජාසියා',
        tamilMeaning: 'දණින් වැටීම',
        arabicName: 'الجاثية',
        verseCount: 37),
    SuraDetails(
        suraNumber: 46,
        tamilName: 'අල් අහ්කාෆ්',
        tamilMeaning: 'වැලි කඳු',
        arabicName: 'الأحقاف',
        verseCount: 35),
    SuraDetails(
        suraNumber: 47,
        tamilName: 'මුහම්මද්',
        arabicName: 'محمد',
        verseCount: 38),
    SuraDetails(
        suraNumber: 48,
        tamilName: 'අල් ෆත්හ්',
        tamilMeaning: 'ජයග‍්‍රහණයන්',
        arabicName: 'الفتح',
        verseCount: 29),
    SuraDetails(
        suraNumber: 49,
        tamilName: 'අල් හුජුරාත්',
        tamilMeaning: 'කාමර',
        arabicName: 'الحجرات',
        verseCount: 18),
    SuraDetails(
        suraNumber: 50,
        tamilName: 'කාෆ්',
        arabicName: 'ق',
        verseCount: 45),
    SuraDetails(
        suraNumber: 51,
        tamilName: 'අද්දාරියාත්',
        tamilMeaning: 'සුළි සුළං',
        arabicName: 'الذاريات',
        verseCount: 60),
    SuraDetails(
        suraNumber: 52,
        tamilName: 'අත්තූර්',
        tamilMeaning: 'කන්ද',
        arabicName: 'الطور',
        verseCount: 49),
    SuraDetails(
        suraNumber: 53,
        tamilName: 'අන්නජ්මු',
        tamilMeaning: 'තාරකාවන්',
        arabicName: 'النجم',
        verseCount: 62),
    SuraDetails(
        suraNumber: 54,
        tamilName: 'අල් කමර්',
        tamilMeaning: 'චන්ද්‍රයා',
        arabicName: 'القمر',
        verseCount: 55),
    SuraDetails(
        suraNumber: 55,
        tamilName: 'අර්රහ්මාන්',
        tamilMeaning: 'අප‍්‍රමාණ දයාබරවන්තයා',
        arabicName: 'الرحمن',
        verseCount: 78),
    SuraDetails(
        suraNumber: 56,
        tamilName: 'අල් වාකිආ',
        tamilMeaning: 'අති විශාල සිද්ධිය',
        arabicName: 'الواقعة',
        verseCount: 96),
    SuraDetails(
        suraNumber: 57,
        tamilName: 'අල් හදීද්',
        tamilMeaning: 'යකඩ',
        arabicName: 'الحديد',
        verseCount: 29),
    SuraDetails(
        suraNumber: 58,
        tamilName: 'අල් මුජාදලා',
        tamilMeaning: 'තර්කය',
        arabicName: 'المجادلة',
        verseCount: 22),
    SuraDetails(
        suraNumber: 59,
        tamilName: 'අල් හෂ්ර්',
        tamilMeaning: 'ඒකරාශී කිරීම',
        arabicName: 'الحشر',
        verseCount: 24),
    SuraDetails(
        suraNumber: 60,
        tamilName: 'අල් මුම්තහනා',
        tamilMeaning: 'පරීක්ෂා කිරීම',
        arabicName: 'الممتحنة',
        verseCount: 13),
    SuraDetails(
        suraNumber: 61,
        tamilName: 'අල් සෆ්',
        tamilMeaning: 'බල ඇණි',
        arabicName: 'الصف',
        verseCount: 14),
    SuraDetails(
        suraNumber: 62,
        tamilName: 'අල් ජුම්ආ',
        tamilMeaning: 'සිකුරාදා',
        arabicName: 'الجمعة',
        verseCount: 11),
    SuraDetails(
        suraNumber: 63,
        tamilName: 'අල් මුනාෆිකූන්',
        tamilMeaning: 'වංචනිකයින්',
        arabicName: 'المنافقون',
        verseCount: 11),
    SuraDetails(
        suraNumber: 64,
        tamilName: 'අත්තකාබුන්',
        tamilMeaning: 'අඩුලූහුඬුකම්',
        arabicName: 'التغابن',
        verseCount: 18),
    SuraDetails(
        suraNumber: 65,
        tamilName: 'අල් තලාක්',
        tamilMeaning: 'දික්කසාදය',
        arabicName: 'الطلاق',
        verseCount: 12),
    SuraDetails(
        suraNumber: 66,
        tamilName: 'අල් තහ්රීම්',
        tamilMeaning: 'තහනම් කිරීම්',
        arabicName: 'التحريم',
        verseCount: 12),
    SuraDetails(
        suraNumber: 67,
        tamilName: 'අල්-මුල්ක්',
        tamilMeaning: 'රාජ්‍ය පාලනය',
        arabicName: 'الملك',
        verseCount: 30),
    SuraDetails(
        suraNumber: 68,
        tamilName: 'අල් කලම්',
        tamilMeaning: 'පෑන',
        arabicName: 'القلم',
        verseCount: 52),
    SuraDetails(
        suraNumber: 69,
        tamilName: 'අල් හාක්කා',
        tamilMeaning: 'සත්‍ය සිද්ධිය',
        arabicName: 'الحاقة',
        verseCount: 52),
    SuraDetails(
        suraNumber: 70,
        tamilName: 'අල් මආරිජ්',
        tamilMeaning: 'උසස් මාර්ගයන්',
        arabicName: 'المعارج',
        verseCount: 44),
    SuraDetails(
        suraNumber: 71,
        tamilName: 'නූහ්',
        arabicName: 'نوح',
        verseCount: 28),
    SuraDetails(
        suraNumber: 72,
        tamilName: 'අල්-ජින්නු',
        tamilMeaning: 'ජින්වරුන්',
        arabicName: 'الجن',
        verseCount: 28),
    SuraDetails(
        suraNumber: 73,
        tamilName: 'අල් මුසම්මිල්',
        tamilMeaning: 'පොරවා ගත් තැනැත්තා',
        arabicName: 'المزمل',
        verseCount: 20),
    SuraDetails(
        suraNumber: 74,
        tamilName: 'අල් මුද්දසිර්',
        tamilMeaning: 'පොරවාගෙන සිටින්නා',
        arabicName: 'المدثر',
        verseCount: 56),
    SuraDetails(
        suraNumber: 75,
        tamilName: 'අල්-කියාමා',
        tamilMeaning: 'විනිශ්චය දිනය (පරලොව)',
        arabicName: 'القيامة',
        verseCount: 40),
    SuraDetails(
        suraNumber: 76,
        tamilName: 'අද්දහ්ර්',
        tamilMeaning: 'කාලය',
        arabicName: 'الانسان',
        verseCount: 31),
    SuraDetails(
        suraNumber: 77,
        tamilName: 'අල් මුර්සලාත්',
        tamilMeaning: 'යවනු ලබන දැය',
        arabicName: 'المرسلات',
        verseCount: 50),
    SuraDetails(
        suraNumber: 78,
        tamilName: 'අන්නබා',
        tamilMeaning: 'අති ශ්‍රේෂ්ඨ පුවත',
        arabicName: 'النبإ',
        verseCount: 40),
    SuraDetails(
        suraNumber: 79,
        tamilName: 'අන්නාසිආත්',
        tamilMeaning: 'තදින් උදුරා ගන්නෝ',
        arabicName: 'النازعات',
        verseCount: 46),
    SuraDetails(
        suraNumber: 80,
        tamilName: 'අබස',
        tamilMeaning: 'කෝපයෙන් වෙව්ලන්නට වූවේය',
        arabicName: 'عبس',
        verseCount: 42),
    SuraDetails(
        suraNumber: 81,
        tamilName: 'අත්තක්වීර්',
        tamilMeaning: 'මැකී යාම (හැකිළී යාම)',
        arabicName: 'التكوير',
        verseCount: 29),
    SuraDetails(
        suraNumber: 82,
        tamilName: 'අල් ඉන්ෆිතාර්',
        tamilMeaning: 'පිපිරී යාම',
        arabicName: 'الإنفطار',
        verseCount: 19),
    SuraDetails(
        suraNumber: 83,
        tamilName: 'අත්තත්ෆීෆ්',
        tamilMeaning: 'මිණුමෙහි වංචා කිරීම',
        arabicName: 'المطففين',
        verseCount: 36),
    SuraDetails(
        suraNumber: 84,
        tamilName: 'අල් ඉන්ෂිකාක්',
        tamilMeaning: 'පැළී දෙකඩ වීම',
        arabicName: 'الإنشقاق',
        verseCount: 25),
    SuraDetails(
        suraNumber: 85,
        tamilName: 'අල් බුරූජ්',
        tamilMeaning: 'ග‍්‍රහ මණ්ඩල',
        arabicName: 'البروج',
        verseCount: 22),
    SuraDetails(
        suraNumber: 86,
        tamilName: 'අත්තාරික්',
        tamilMeaning: 'අළුයම් තාරකාව',
        arabicName: 'الطارق',
        verseCount: 17),
    SuraDetails(
        suraNumber: 87,
        tamilName: 'අල් අඃලා',
        tamilMeaning: 'අති ශ්‍රේෂ්ඨයෙකි',
        arabicName: 'الأعلى',
        verseCount: 19),
    SuraDetails(
        suraNumber: 88,
        tamilName: 'අල් ඝාෂියා',
        tamilMeaning: 'වටකර ගැනීම',
        arabicName: 'الغاشية',
        verseCount: 26),
    SuraDetails(
        suraNumber: 89,
        tamilName: 'අල් ෆජ්ර්',
        tamilMeaning: 'අළුයම් කාලය',
        arabicName: 'الفجر',
        verseCount: 30),
    SuraDetails(
        suraNumber: 90,
        tamilName: 'අල් බලද්',
        tamilMeaning: 'නගරය',
        arabicName: 'البلد',
        verseCount: 20),
    SuraDetails(
        suraNumber: 91,
        tamilName: 'අල් ෂම්ස්',
        tamilMeaning: 'සූර්යා',
        arabicName: 'الشمس',
        verseCount: 15),
    SuraDetails(
        suraNumber: 92,
        tamilName: 'අල් ලයිල්',
        tamilMeaning: 'රාත‍්‍රිය',
        arabicName: 'الليل',
        verseCount: 21),
    SuraDetails(
        suraNumber: 93,
        tamilName: 'අල් ලූහා',
        tamilMeaning: 'පෙරවරුව',
        arabicName: 'الضحى',
        verseCount: 11),
    SuraDetails(
        suraNumber: 94,
        tamilName: 'අලම් නෂ්රහ්',
        tamilMeaning: 'අපි විස්තීරණය කළේ නැද්ද?',
        arabicName: 'الشرح',
        verseCount: 8),
    SuraDetails(
        suraNumber: 95,
        tamilName: 'අත්තීන්',
        tamilMeaning: 'අත්තික්කා',
        arabicName: 'التين',
        verseCount: 8),
    SuraDetails(
        suraNumber: 96,
        tamilName: 'අල් අලක්',
        tamilMeaning: 'ලේ කැටිය',
        arabicName: 'العلق',
        verseCount: 19),
    SuraDetails(
        suraNumber: 97,
        tamilName: 'අල් කද්ර්',
        tamilMeaning: 'ඉමහත් ගෞරවයෙන් යුත් රාත‍්‍රිය',
        arabicName: 'القدر',
        verseCount: 5),
    SuraDetails(
        suraNumber: 98,
        tamilName: 'අල් බයියිනා',
        tamilMeaning: 'පැහැදිලි සාධකය',
        arabicName: 'البينة',
        verseCount: 8),
    SuraDetails(
        suraNumber: 99,
        tamilName: 'අල් සිල්සාලහා',
        tamilMeaning: 'භූමි කම්පාව',
        arabicName: 'الزلزلة',
        verseCount: 8),
    SuraDetails(
        suraNumber: 100,
        tamilName: 'අල් ආදියාත්',
        tamilMeaning: 'වේගයෙන් දුවන්නවුන්',
        arabicName: 'العاديات',
        verseCount: 11),
    SuraDetails(
        suraNumber: 101,
        tamilName: 'අල් කාරිආ',
        tamilMeaning: 'තිගැස්සෙන සුළු සිද්ධිය',
        arabicName: 'القارعة',
        verseCount: 11),
    SuraDetails(
        suraNumber: 102,
        tamilName: 'අත්තකාසුර්',
        tamilMeaning: 'තන්හාව',
        arabicName: 'التكاثر',
        verseCount: 8),
    SuraDetails(
        suraNumber: 103,
        tamilName: 'අල් අස්ර්',
        tamilMeaning: 'කාලය',
        arabicName: 'العصر',
        verseCount: 3),
    SuraDetails(
        suraNumber: 104,
        tamilName: 'අල් හුමසා',
        tamilMeaning: 'ඕපාදූප කීම',
        arabicName: 'الهمزة',
        verseCount: 9),
    SuraDetails(
        suraNumber: 105,
        tamilName: 'අල් ෆීල්',
        tamilMeaning: 'ඇතා',
        arabicName: 'الفيل',
        verseCount: 5),
    SuraDetails(
        suraNumber: 106,
        tamilName: 'කුරයිෂ්',
        tamilMeaning: 'කුරයිෂිවරුන්',
        arabicName: 'قريش',
        verseCount: 4),
    SuraDetails(
        suraNumber: 107,
        tamilName: 'අල් මාඌන්',
        tamilMeaning: 'අල්ප වස්තූන්',
        arabicName: 'الماعون',
        verseCount: 7),
    SuraDetails(
        suraNumber: 108,
        tamilName: 'අල් කව්සර්',
        tamilMeaning: 'අප‍්‍රමාණ සැප සම්පත්',
        arabicName: 'الكوثر',
        verseCount: 3),
    SuraDetails(
        suraNumber: 109,
        tamilName: 'අල් කාෆිරූන්',
        tamilMeaning: 'ප‍්‍රතික්ෂේප කරන්නන්',
        arabicName: 'الكافرون',
        verseCount: 6),
    SuraDetails(
        suraNumber: 110,
        tamilName: 'අන්නස්ර්',
        tamilMeaning: 'අති මහත් උදව්ව',
        arabicName: 'النصر',
        verseCount: 3),
    SuraDetails(
        suraNumber: 111,
        tamilName: 'අල් ලහබ්',
        tamilMeaning: 'ඇවිලෙන ගින්න',
        arabicName: 'المسد',
        verseCount: 5),
    SuraDetails(
        suraNumber: 112,
        tamilName: 'අල් ඉහ්ලාස්',
        tamilMeaning: 'ඒකීයත්වය',
        arabicName: 'الإخلاص',
        verseCount: 4),
    SuraDetails(
        suraNumber: 113,
        tamilName: 'අල් ෆලක්',
        tamilMeaning: 'අළුයම',
        arabicName: 'الفلق',
        verseCount: 5),
    SuraDetails(
        suraNumber: 114,
        tamilName: 'අන්නාස්',
        tamilMeaning: 'මිනිසුන්',
        arabicName: 'الناس',
        verseCount: 6)
  ];
}
